# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                      # Number of pages shown in the pagination menu
    default_options:
        page_name: page                # Query parameter name for the page number
        sort_field_name: sort          # Query parameter name for the sort field
        sort_direction_name: direction # Query parameter name for the sort direction
        distinct: true                 # Ensure distinct results
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Default template