knp_paginator:
    page_range: 5
    default_options:
        page_name: page  # Name of the query parameter for pagination
        sort_field_name: sort
        sort_direction_name: direction
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
