framework:
    messenger:
        failure_transport: failed

        transports:
            # async:  # <-- Commentez/désactivez le transport asynchrone
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     options:
            #         use_notify: true
            #         check_delayed_interval: 60000
            #     retry_strategy:
            #         max_retries: 3
            #         multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Supprimez/Commentez ces lignes pour désactiver le routage des emails via Messenger
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async