security:
    
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur: 'auto'
        App\Entity\Administrateur: 'auto'
        App\Entity\Fournisseur: 'auto'

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /

    access_control:
        # Admin routes
        - { path: ^/admin, roles: PUBLIC_ACCESS }

        - { path: ^/homeadmin, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_ADMIN }


        # Public login route
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Authenticated homepage
        - { path: ^/home, roles: ROLE_USER }

        # Everything else requires auth
        - { path: ^/, roles: PUBLIC_ACCESS }

        # Public routes
        - { path: ^/register, roles: PUBLIC_ACCESS }
    


