controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_dashboard:
    path: /app_dashboard
    controller: App\Controller\PageController::dashboard
    # config/routes.yaml
admin_statistics:
    path: /admin/statistics
    controller: App\Controller\RegistrationController::statistics

fc_load_events:
    path: /fc-load-events
    controller: App\Controller\CalendarController::load
    methods: [GET] # FullCalendar uses GET by default


