controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_dashboard:
    path: /app_dashboard
    controller: App\Controller\PageController::dashboard
    # config/routes.yaml
admin_statistics:
    path: /admin/statistics
    controller: App\Controller\RegistrationController::statistics
# config/routes.yaml
forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityMailController::forgotPassword
    methods: [GET, POST]
reset_password:
    path: /reset-password/{token}
    controller: App\Controller\SecurityMailController::resetPassword
    methods: [GET, POST]
