# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    terrain_photos_directory: '%kernel.project_dir%/public/uploads/terrain_photos'
    image: 'http://picsum.photos/id/<numberBetween(400,800)>/200/180'

services:
    App\Service\PaginatorProxy:
        arguments:
            $paginator: '@knp_paginator'


    # Default configuration for services
    _defaults:
        autowire: true      # Automatically inject dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes all classes in src/ available as services except excluded ones
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # ✅ Ensure Entities can be autowired (fixing exclusion issue)
    App\Entity\Categorie: ~

    # Pdf Contract Generator Service
    App\Service\PdfContractGenerator: ~

    # OpenWeatherService with API key argument from .env
    App\Service\OpenWeatherService:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'

    # Add more service definitions when explicit configuration is needed
    # Note: Last definitions *replace* previous ones
