# config/services.yaml
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\EventSubscriber\CalendarSubscriber:
        # CalendarBundle\Controller\CalendarController: '@App\EventSubscriber\CalendarSubscriber'
    

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Entity/'
        
    # Explicit service definition
        # App\Security\AuthenticationSuccessHandler:
        #     arguments:
        #          $urlGenerator: '@router'


    # add more service definitions when explicit configuration is needed

    # App\Services\QrCodeGenerator:
    #     arguments:
    #         $builder: '@Endroid\QrCode\Builder\Builder'
    


    # please note that last definitions always *replace* previous ones
    # Explicit service definition
 